# Permalinks
#
# Use of `relative_permalinks` ensures post links from the index work properly.
permalink:           pretty
relative_permalinks: true

# Setup
title:               Lanyon
tagline:             'A Jekyll theme'
description:         'A reserved <a href="http://jekyllrb.com" target="_blank">Jekyll</a> theme that places the utmost gravity on content with a hidden drawer. Made by <a href="https://twitter.com/mdo" target="_blank">@mdo</a>.'
url:                 http://mattwarren.github.io
baseurl:             ''
paginate:            5

# About/contact
author:
  name:              Matt Warren
  url:               https://twitter.com/matthewwarren
  email:             matt.warren@live.co.uk

# Custom vars
version:             1.0.0

# Use the following plug-ins
gems:
  - jekyll-sitemap # Create a sitemap using the official Jekyll sitemap gem
  - redcarpet

# See http://milanaryal.com/2015/writing-on-github-pages-and-jekyll-using-markdown/
# and http://ajoz.github.io/2014/06/29/i-want-my-github-flavored-markdown/
# For tables see https://george-hawkins.github.io/basic-gfm-jekyll/redcarpet-extensions.html
markdown: redcarpet
#redcarpet:
#  extensions: ["no_intra_emphasis", "fenced_code_blocks", "autolink", "tables", "with_toc_data"]
